SET DATEFIRST 7
SET ANSI_NULLS OFF
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET LOCK_TIMEOUT -1
SET QUOTED_IDENTIFIER OFF
GO
--SELECT dbo.fnDICOPrimerDiaMes(1,2023)
IF EXISTS(SELECT * FROM sysobjects WHERE TYPE='fn' AND NAME='fnDICOPrimerDiaMes')
DROP FUNCTION fnDICOPrimerDiaMes
GO
CREATE FUNCTION fnDICOPrimerDiaMes(@Periodo	INT, @Ejercicio INT)
RETURNS DATETIME
AS
BEGIN
	DECLARE @DiaString VARCHAR(20),
		  @Resultado  DATETIME
		  
    SELECT @DiaString='01/'+CAST(@Periodo AS CHAR(2))+'/'+CAST(@Ejercicio AS CHAR(4))
    
    SELECT @Resultado=CAST(@DiaString AS DATETIME)		  

RETURN  @Resultado
END
